; This file was auto-generated by drush make
; drush dl drupal
; cd drupal-*
; drush dl backup_migrate ctools ckeditor context devel ds features fences i18n i18nviews imce jquery_update l10n_client l10n_update oembed metatag panels pathauto realname strongarm superfish tagadelic taxonomy_menu token transliteration variable views wysiwyg_filter service_links
; wget https://drupal.org/files/i18n_string-Support-text-format-elements-fix-1252144.patch
; cd sites/all/modules/i18n
; patch -p1 < ../i18n_string-Support-text-format-elements-fix-1252144.patch

core = 7.x

api = 2
projects[drupal][version] = "7.23"

; Profiles
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dp7vi][download][type] = "git"
projects[dp7vi][download][url] = "https://github.com/dinhtrung/dp7vi.git"
projects[dp7vi][type] = "profile"

; Modules
projects[] = "backup_migrate"
projects[] = "ctools"
projects[] = "ckeditor"
projects[] = "context"
projects[] = "devel"
projects[] = "ds"
projects[] = "features"
projects[] = "fences"
projects[i18n] = "i18n"
projects[i18n][patch][1252144] = https://drupal.org/files/i18n_string-Support-text-format-elements-fix-1252144.patch
projects[] = "i18nviews"
projects[] = "imce"
projects[] = "jquery_update"
projects[] = "l10n_client"
projects[] = "l10n_update"
projects[] = "oembed"
projects[] = "metatag"
projects[] = "service_links"
projects[] = "panels"
projects[] = "pathauto"
projects[] = "realname"
projects[] = "strongarm"
projects[] = "superfish"
projects[] = "tagadelic"
projects[] = "taxonomy_menu"
projects[] = "token"
projects[] = "transliteration"
projects[] = "variable"
projects[] = "views"
projects[] = "wysiwyg_filter"

