; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[backup_migrate][version] = "2.7"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[features][version] = "2.0-rc1"

projects[fences][version] = "1.0"

projects[i18n][version] = "1.9"

projects[i18nviews][version] = "3.x-dev"

projects[l10n_client][version] = "1.2"

projects[l10n_update][version] = "1.0-beta3"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[tagadelic][version] = "2.x-dev"

projects[taxonomy_menu][version] = "1.4"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[variable][version] = "2.2"

projects[views][version] = "3.7"

projects[wysiwyg_filter][version] = "1.6-rc2"

